#!/bin/bash

set -o errexit -o nounset -o pipefail

generate() {
    echo $1
    qrencode -s 1 -o $1 $2
    gm identify -format '%w×%h\n' $1
    zopflipng -ym $1 $1
}

generate static/donate-bitcoin.png 'bitcoin:bc1qj4nxpfhsgj3f7w8c2689kq865apfla2jyxgaem?label=secureblue&message=Donation%20to%20secureblue'
generate static/donate-monero.png 'monero:43fry9taGiwhAtNYEZNfssdzJ8Ra12ewAbQoVsvFzoLS6qMSgsE2FvE7xY52rAnKjPL5r2N88KYvqXpthUfSwa23K1BBMD9?recipient_name=secureblue&tx_description=Donation%20to%20secureblue'
generate static/donate-ethereum.png 'ethereum:0x10289B51aEF109BBc07F68341F2Df8Ef60a5b618'
generate static/donate-litecoin.png 'litecoin:ltc1q65hpetza8stgje640pcn25mef6xpdzxqazcawq?label=secureblue&message=Donation%20to%20secureblue'
